version: 0.2

phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Building src folder with Babel and copying config.json into build/...
      - ./node_modules/.bin/babel src -d build && mkdir build/config && cp src/config/config.json build/config
artifacts:
  files:
    - "build/**/*"
  discard-paths: yes
